# frozen_string_literal: true

module Rubast
  module IR
    Program = Data.define(:statements, :locals, :warnings)
    ClassDefinition = Data.define(:name, :superclass, :definitions, :span)
    MethodDefinition = Data.define(:name, :parameters, :locals, :body, :span)
    Sequence = Data.define(:expressions, :result_type, :span)
    BooleanLiteral = Data.define(:value, :span)
    IntegerType = Data.define(:minimum, :maximum)
    SymbolType = Data.define(:name)
    HashShape = Data.define(:keys)
    UnionType = Data.define(:types)
    Operation = Data.define(:name, :operands, :result_type, :span)
    Conditional = Data.define(:predicate, :consequent, :alternative, :result_type, :span)
    Return = Data.define(:value, :span)
    Loop = Data.define(:predicate, :body, :until_loop, :post_test, :result_type, :span)
    LoopExit = Data.define(:kind, :value, :span)
    NilLiteral = Data.define(:span)
    ConstantRead = Data.define(:name, :span)
    ObjectType = Data.define(:class_name, :fields)
    NewObject = Data.define(:class_name, :arguments, :parameters, :locals, :body, :result_type, :span)
    SelfRead = Data.define(:result_type, :span)
    InstanceRead = Data.define(:name, :result_type, :span)
    InstanceWrite = Data.define(:name, :value, :span)
    MethodCall = Data.define(:class_name, :name, :receiver, :arguments, :parameters, :locals, :body, :result_type,
                             :span)
    Yield = Data.define(:arguments, :result_type, :span)
    YieldInvoke = Data.define(:arguments, :parameters, :locals, :body, :result_type, :span)
    BlockInvocation = Data.define(:invocation, :result_type, :span)
    Block = Data.define(:parameters, :locals, :body, :span)
    BlockCall = Data.define(:call, :block, :result_type, :span)
    Iterator = Data.define(:name, :family, :receiver, :parameters, :locals, :steps, :result_type, :span)
    BlockStep = Data.define(:index, :body, :span)
    Call = Data.define(:name, :receiver, :arguments, :safe_navigation, :span)
    Super = Data.define(:arguments, :forward_arguments, :span)
    IntegerLiteral = Data.define(:value, :span)
    StringLiteral = Data.define(:value, :frozen, :span)
    SymbolLiteral = Data.define(:value, :span)
    HashLiteral = Data.define(:elements, :result_type, :span)
    ArrayLiteral = Data.define(:elements, :result_type, :span)
    IndexWrite = Data.define(:receiver, :index, :value, :result_type, :span)
    Builtin = Data.define(:family, :name, :receiver, :arguments, :result_type, :span)
    InterpolatedString = Data.define(:parts, :span)
    LocalWrite = Data.define(:name, :value, :span)
    LocalRead = Data.define(:name, :span)
    GetLine = Data.define(:span)
    SafeChomp = Data.define(:receiver, :span)
    Puts = Data.define(:value, :span)
  end
end
