AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "target/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Metrics/AbcSize:
  Max: 27

Metrics/MethodLength:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 8
